// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModVox.Web.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModVox.Web.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ModVoxDbContext))]
    [Migration("20260517213232_BaselineReset")]
    partial class BaselineReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModVox.Web.Domain.AccountSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("session_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_account_sessions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_account_sessions_user_id");

                    b.ToTable("account_sessions");
                });

            modelBuilder.Entity("ModVox.Web.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_log_created_at");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_audit_log_event_type");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("ModVox.Web.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_games_slug");

                    b.ToTable("games");
                });

            modelBuilder.Entity("ModVox.Web.Domain.Mod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangelogHtml")
                        .HasColumnType("text")
                        .HasColumnName("changelog_html");

                    b.Property<string>("ChangelogMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("changelog_markdown");

                    b.Property<string>("ChangelogPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("changelog_path");

                    b.Property<DateTimeOffset?>("ContentFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("content_fetched_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Credits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("credits");

                    b.Property<string>("DefaultRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("default_ref");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("bigint")
                        .HasColumnName("download_count");

                    b.Property<string>("ExternalCredits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("external_credits");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("ImagesFolder")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("images_folder");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_hash");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<DateTimeOffset?>("LastAcceptedRefreshAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accepted_refresh_at");

                    b.Property<Guid>("MaintainerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintainer_user_id");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("moderation_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("ReadmeHtml")
                        .HasColumnType("text")
                        .HasColumnName("readme_html");

                    b.Property<string>("ReadmeMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("readme_markdown");

                    b.Property<string>("ReadmePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("readme_path");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("repository");

                    b.Property<Guid[]>("TagIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("tag_ids");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerifyToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("verify_token");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_mods_game_id");

                    b.HasIndex("KeyHash")
                        .HasDatabaseName("ix_mods_key_hash");

                    b.HasIndex("MaintainerUserId")
                        .HasDatabaseName("ix_mods_maintainer_user_id");

                    b.HasIndex("ModerationStatus")
                        .HasDatabaseName("ix_mods_moderation_status");

                    b.HasIndex("Provider", "Owner", "Repository")
                        .IsUnique()
                        .HasDatabaseName("ix_mods_coordinates");

                    b.ToTable("mods");
                });

            modelBuilder.Entity("ModVox.Web.Domain.ModRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsPrerelease")
                        .HasColumnType("boolean")
                        .HasColumnName("is_prerelease");

                    b.Property<Guid>("ModId")
                        .HasColumnType("uuid")
                        .HasColumnName("mod_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tag_name");

                    b.HasKey("Id");

                    b.HasIndex("ModId")
                        .HasDatabaseName("ix_mod_releases_mod_id");

                    b.HasIndex("ModId", "TagName")
                        .IsUnique()
                        .HasDatabaseName("ix_mod_releases_mod_tag");

                    b.ToTable("mod_releases");
                });

            modelBuilder.Entity("ModVox.Web.Domain.ModReleaseArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("download_url");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.HasIndex("DownloadUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_mod_release_artifacts_download_url");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_mod_release_artifacts_release_id");

                    b.ToTable("mod_release_artifacts");
                });

            modelBuilder.Entity("ModVox.Web.Domain.ModReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid>("ModId")
                        .HasColumnType("uuid")
                        .HasColumnName("mod_id");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("report_type");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ModId")
                        .HasDatabaseName("ix_mod_reports_mod_id");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_mod_reports_status");

                    b.ToTable("mod_reports");
                });

            modelBuilder.Entity("ModVox.Web.Domain.RefreshJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ModId")
                        .HasColumnType("uuid")
                        .HasColumnName("mod_id");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ref");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("repository");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ModId")
                        .HasDatabaseName("ix_refresh_jobs_mod_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_refresh_jobs_status");

                    b.HasIndex("ModId", "IdempotencyKey")
                        .HasDatabaseName("ix_refresh_jobs_mod_idempotency");

                    b.ToTable("refresh_jobs");
                });

            modelBuilder.Entity("ModVox.Web.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_label");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("ModVox.Web.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BanExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_expires_at");

                    b.Property<string>("BanType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ban_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("MustChangeCredentials")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_credentials");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("session_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ModVox.Web.Domain.AccountSession", b =>
                {
                    b.HasOne("ModVox.Web.Domain.UserAccount", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModVox.Web.Domain.AuditLog", b =>
                {
                    b.HasOne("ModVox.Web.Domain.UserAccount", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("ModVox.Web.Domain.Mod", b =>
                {
                    b.HasOne("ModVox.Web.Domain.Game", "Game")
                        .WithMany("Mods")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModVox.Web.Domain.UserAccount", "MaintainerUser")
                        .WithMany("Mods")
                        .HasForeignKey("MaintainerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("MaintainerUser");
                });

            modelBuilder.Entity("ModVox.Web.Domain.ModRelease", b =>
                {
                    b.HasOne("ModVox.Web.Domain.Mod", "Mod")
                        .WithMany("Releases")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("ModVox.Web.Domain.ModReleaseArtifact", b =>
                {
                    b.HasOne("ModVox.Web.Domain.ModRelease", "Release")
                        .WithMany("Artifacts")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("ModVox.Web.Domain.ModReport", b =>
                {
                    b.HasOne("ModVox.Web.Domain.Mod", "Mod")
                        .WithMany("Reports")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModVox.Web.Domain.UserAccount", "ReporterUser")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModVox.Web.Domain.UserAccount", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mod");

                    b.Navigation("ReporterUser");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("ModVox.Web.Domain.RefreshJob", b =>
                {
                    b.HasOne("ModVox.Web.Domain.Mod", "Mod")
                        .WithMany("RefreshJobs")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("ModVox.Web.Domain.Game", b =>
                {
                    b.Navigation("Mods");
                });

            modelBuilder.Entity("ModVox.Web.Domain.Mod", b =>
                {
                    b.Navigation("RefreshJobs");

                    b.Navigation("Releases");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("ModVox.Web.Domain.ModRelease", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("ModVox.Web.Domain.UserAccount", b =>
                {
                    b.Navigation("Mods");

                    b.Navigation("Reports");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
