namespace ModVox.Web.Domain;

public sealed record ModRecord(
    Guid Id,
    Guid GameId,
    Guid MaintainerUserId,
    string Provider,
    string Owner,
    string Repository,
    string DefaultRef,
    string Name,
    string Description,
    string ReadmePath,
    string ChangelogPath,
    string ImagesFolder,
    IReadOnlyList<Guid> TagIds,
    IReadOnlyDictionary<string, string> Credits,
    long DownloadCount,
    string ModerationStatus,
    string VerifyToken,
    string? KeyHash,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? LastAcceptedRefreshAt,
    int KeyVersion);
